/**
 * ONES AI — Master SEO topic cluster list
 * 500+ pre-planned article titles organized by tier.
 * Used by the automated daily blog-generation scheduler.
 *
 * Tiers
 *  pillar        — broad authority pages (1-2 per cluster, 2500+ words)
 *  system        — ONES proprietary system blends
 *  ingredient    — individual ingredient deep-dives
 *  comparison    — product / brand / form comparisons
 *  symptom       — symptom-first discovery intent
 *  lab           — lab marker / biomarker explainers
 *  lifestyle     — biohacking, sleep, stress, longevity
 */

export interface TopicCluster {
  title: string;
  category: string;
  tier: 'pillar' | 'system' | 'ingredient' | 'comparison' | 'symptom' | 'lab' | 'lifestyle';
  primaryKeyword: string;
  secondaryKeywords: string[];
  /** Monthly US search volume — populated by scripts/keyword-research.cjs */
  volume?: number;
  /** Keyword difficulty 0–100 (DataForSEO competition_index) */
  kd?: number;
  /** Cost-per-click USD (signal of commercial intent) */
  cpc?: number;
}

export const TOPIC_CLUSTERS: TopicCluster[] = [

  // ── PILLAR ────────────────────────────────────────────────────────────────
  { tier: 'pillar', title: 'The Complete Guide to personalized Supplements: How to Build a Formula for Your Biology', category: 'personalized Health', primaryKeyword: 'personalized supplements', secondaryKeywords: ['custom supplement formula', 'blood test supplements', 'personalized nutrition'] },
  { tier: 'pillar', title: 'How to Read Your Blood Test Results: A Plain-English Guide to Every Marker', category: 'Lab Results', primaryKeyword: 'how to read blood test results', secondaryKeywords: ['blood test markers explained', 'CBC interpretation', 'metabolic panel guide'] },
  { tier: 'pillar', title: 'The Science of Biohacking: Evidence-Based Strategies for Peak Performance', category: 'Biohacking', primaryKeyword: 'biohacking guide', secondaryKeywords: ['evidence-based biohacking', 'performance optimization', 'longevity protocols'] },
  { tier: 'pillar', title: 'Hormonal Health 101: The Complete Roadmap for Men and Women', category: 'Hormonal Health', primaryKeyword: 'hormonal health guide', secondaryKeywords: ['hormone optimization', 'endocrine system support', 'hormonal imbalance treatment'] },
  { tier: 'pillar', title: 'The Ultimate Guide to Sleep optimization: Supplements, Habits, and Lab Markers', category: 'Sleep', primaryKeyword: 'sleep optimization guide', secondaryKeywords: ['best supplements for sleep', 'how to improve sleep quality', 'sleep lab markers'] },
  { tier: 'pillar', title: 'Gut Health Deep Dive: Microbiome, Digestion, and the Supplements That Actually Work', category: 'Gut Health', primaryKeyword: 'gut health guide', secondaryKeywords: ['microbiome supplements', 'best probiotics', 'digestive health protocol'] },
  { tier: 'pillar', title: 'Energy optimization: The Root Causes of Fatigue and How to Fix Them', category: 'Energy', primaryKeyword: 'energy optimization supplements', secondaryKeywords: ['chronic fatigue causes', 'best energy supplements', 'adrenal fatigue protocol'] },
  { tier: 'pillar', title: 'Cognitive Performance: The Brain-Health Stack Backed by Research', category: 'Cognitive Health', primaryKeyword: 'cognitive performance supplements', secondaryKeywords: ['nootropic stack', 'brain health supplements', 'memory and focus supplements'] },
  { tier: 'pillar', title: 'Longevity Science: What the Research Says About Living Longer and Healthier', category: 'Longevity', primaryKeyword: 'longevity supplements', secondaryKeywords: ['anti-aging supplements', 'NAD+ longevity', 'healthspan extension'] },
  { tier: 'pillar', title: 'Women\'s Hormonal Health: The Evidence-Based Supplement Protocol by Life Stage', category: 'Women\'s Health', primaryKeyword: 'women\'s hormonal health supplements', secondaryKeywords: ['menopause supplements', 'perimenopause protocol', 'PCOS supplement stack'] },
  { tier: 'pillar', title: 'Men\'s Health optimization: Testosterone, Energy, and Longevity Protocols', category: 'Men\'s Health', primaryKeyword: 'men\'s health supplements', secondaryKeywords: ['testosterone support supplements', 'male vitality protocol', 'men\'s energy stack'] },
  { tier: 'pillar', title: 'Metabolic Health: Blood Sugar, Insulin Resistance, and the Supplement Protocol', category: 'Metabolic Health', primaryKeyword: 'metabolic health supplements', secondaryKeywords: ['blood sugar regulation supplements', 'insulin resistance support', 'glucose control stack'] },

  // ── SYSTEM BLENDS ─────────────────────────────────────────────────────────
  { tier: 'system', title: 'Adrenal Support: What It Is, Who Needs It, and the Clinical Evidence Behind the Formula', category: 'Supplements', primaryKeyword: 'adrenal support supplement', secondaryKeywords: ['adrenal fatigue recovery', 'cortisol regulation', 'HPA axis support'] },
  { tier: 'system', title: 'Liver Support Supplements: How to Protect and Detoxify Your Body\'s Largest Metabolic Organ', category: 'Supplements', primaryKeyword: 'liver support supplement', secondaryKeywords: ['liver detox supplements', 'NAC liver health', 'milk thistle silymarin'] },
  { tier: 'system', title: 'Heart Support Formula: The Cardioprotective Nutrients Cardiologists Discuss Most', category: 'Supplements', primaryKeyword: 'heart health supplements', secondaryKeywords: ['CoQ10 heart health', 'omega-3 cardiovascular support', 'magnesium heart rhythm'] },
  { tier: 'system', title: 'Thyroid Support: Nutrients That Affect T3, T4, and Conversion — What the Evidence Shows', category: 'Supplements', primaryKeyword: 'thyroid support supplement', secondaryKeywords: ['selenium thyroid', 'iodine thyroid health', 'T4 to T3 conversion nutrients'] },
  { tier: 'system', title: 'Endocrine Support: Balancing the Hormonal Orchestra With Targeted Nutrition', category: 'Supplements', primaryKeyword: 'endocrine support supplement', secondaryKeywords: ['hormone balance supplement', 'endocrine system nutrients', 'adaptogen stack'] },
  { tier: 'system', title: 'Histamine Intolerance and Supplement Support: The DAO Enzyme Connection', category: 'Supplements', primaryKeyword: 'histamine intolerance supplements', secondaryKeywords: ['DAO enzyme supplement', 'low histamine diet', 'quercetin histamine'] },
  { tier: 'system', title: 'Lung Support Supplements: Respiratory Health Nutrients Backed by Research', category: 'Supplements', primaryKeyword: 'lung health supplements', secondaryKeywords: ['NAC respiratory health', 'quercetin lung function', 'vitamin D immunity lungs'] },
  { tier: 'system', title: 'Kidney and Bladder Health: The Nutritional Protocol for Urinary Tract Support', category: 'Supplements', primaryKeyword: 'kidney health supplements', secondaryKeywords: ['bladder health supplements', 'kidney stone prevention', 'cranberry extract UTI'] },
  { tier: 'system', title: 'Beta Max Explained: The Thermogenic and Metabolic Support Formula for Body Composition', category: 'Supplements', primaryKeyword: 'metabolic support supplement', secondaryKeywords: ['thermogenic supplement', 'fat burning supplements evidence', 'body composition stack'] },
  { tier: 'system', title: 'Immune-C Formula: Vitamin C, Zinc, and the Synergistic Ingredients That Fortify Immunity', category: 'Supplements', primaryKeyword: 'immune support supplement', secondaryKeywords: ['vitamin C immune function', 'zinc immunity', 'elderberry immune support'] },
  { tier: 'system', title: 'Magnesium Complex: Why Seven Forms Are Better Than One', category: 'Supplements', primaryKeyword: 'magnesium complex supplement', secondaryKeywords: ['magnesium glycinate', 'magnesium malate benefits', 'best form of magnesium'] },
  { tier: 'system', title: 'Ligament Support: Collagen, Silica, and the Connective Tissue Repair Protocol', category: 'Supplements', primaryKeyword: 'ligament support supplement', secondaryKeywords: ['collagen for joints', 'connective tissue supplement', 'joint repair nutrition'] },

  // ── INGREDIENT DEEP-DIVES ─────────────────────────────────────────────────
  { tier: 'ingredient', title: 'Ashwagandha (KSM-66): Stress, Cortisol, and the Clinical Data on 600 mg', category: 'Supplements', primaryKeyword: 'ashwagandha KSM-66', secondaryKeywords: ['ashwagandha cortisol', 'ashwagandha dosage', 'adaptogen for stress'] },
  { tier: 'ingredient', title: 'Omega-3 EPA and DHA: The Dose, Form, and Frequency That Actually Makes a Difference', category: 'Supplements', primaryKeyword: 'omega-3 EPA DHA supplement', secondaryKeywords: ['fish oil vs algae oil', 'EPA DHA ratio inflammation', 'omega-3 bioavailability'] },
  { tier: 'ingredient', title: 'Vitamin D3 and K2: Why You Should Never Take One Without the Other', category: 'Supplements', primaryKeyword: 'vitamin D3 K2 supplement', secondaryKeywords: ['vitamin D deficiency', 'MK-7 vs MK-4', 'calcium and vitamin D3 K2'] },
  { tier: 'ingredient', title: 'Magnesium Glycinate: The Superior Form for Sleep, Anxiety, and Muscle Recovery', category: 'Supplements', primaryKeyword: 'magnesium glycinate supplement', secondaryKeywords: ['magnesium for sleep', 'magnesium deficiency symptoms', 'best magnesium for anxiety'] },
  { tier: 'ingredient', title: 'CoQ10 and Ubiquinol: Mitochondrial Energy and Cardiovascular Protection Explained', category: 'Supplements', primaryKeyword: 'CoQ10 ubiquinol supplement', secondaryKeywords: ['CoQ10 heart health', 'ubiquinol vs ubiquinone', 'CoQ10 statin depletion'] },
  { tier: 'ingredient', title: 'NMN: The NAD+ Precursor Turning Heads in Longevity Research', category: 'Supplements', primaryKeyword: 'NMN supplement', secondaryKeywords: ['NMN vs NR', 'NAD+ and aging', 'NMN dosage evidence'] },
  { tier: 'ingredient', title: 'Rhodiola Rosea: The Adaptogen for Mental Fatigue, Focus, and Resilience', category: 'Supplements', primaryKeyword: 'rhodiola rosea supplement', secondaryKeywords: ['rhodiola for stress', 'rhodiola dosage', 'adaptogen focus energy'] },
  { tier: 'ingredient', title: 'NAC (N-Acetyl Cysteine): Glutathione Production, Detox, and Respiratory Benefits', category: 'Supplements', primaryKeyword: 'NAC supplement', secondaryKeywords: ['NAC glutathione', 'NAC detoxification', 'NAC respiratory health'] },
  { tier: 'ingredient', title: 'Zinc: Deficiency Signs, Immunity, Testosterone, and the Right Form to Take', category: 'Supplements', primaryKeyword: 'zinc supplement benefits', secondaryKeywords: ['zinc deficiency symptoms', 'zinc picolinate vs gluconate', 'zinc testosterone'] },
  { tier: 'ingredient', title: 'Selenium: Thyroid Enzymes, Antioxidant Defense, and the SeMet Advantage', category: 'Supplements', primaryKeyword: 'selenium supplement', secondaryKeywords: ['selenomethionine absorption', 'selenium thyroid health', 'selenium antioxidant'] },
  { tier: 'ingredient', title: 'Berberine: Blood Sugar, Cholesterol, and the Metformin Comparison', category: 'Supplements', primaryKeyword: 'berberine supplement', secondaryKeywords: ['berberine blood sugar', 'berberine vs metformin', 'berberine cholesterol'] },
  { tier: 'ingredient', title: 'Lion\'s Mane Mushroom: Neurogenesis, BDNF, and Cognitive Benefits', category: 'Supplements', primaryKeyword: 'lion\'s mane mushroom supplement', secondaryKeywords: ['lion\'s mane BDNF', 'lion\'s mane cognition', 'mushroom nootropic stack'] },
  { tier: 'ingredient', title: 'Reishi Mushroom: Immune Modulation, Stress, and the Beta-Glucan Mechanism', category: 'Supplements', primaryKeyword: 'reishi mushroom supplement', secondaryKeywords: ['reishi immune support', 'beta-glucans reishi', 'adaptogen mushroom'] },
  { tier: 'ingredient', title: 'Vitamin K2 MK-7: Bones, Arteries, and Why Most People Are Deficient', category: 'Supplements', primaryKeyword: 'vitamin K2 MK-7', secondaryKeywords: ['K2 arterial calcification', 'vitamin K2 bones', 'MK-7 dosage'] },
  { tier: 'ingredient', title: 'Collagen Peptides: Types I, II, III and the Evidence for Skin, Joints, and Gut', category: 'Supplements', primaryKeyword: 'collagen peptides supplement', secondaryKeywords: ['collagen for skin', 'collagen joints research', 'hydrolysed collagen bioavailability'] },
  { tier: 'ingredient', title: 'Creatine Monohydrate: Cognitive Performance, Muscle, and Long-Term Safety Data', category: 'Supplements', primaryKeyword: 'creatine monohydrate supplement', secondaryKeywords: ['creatine for cognition', 'creatine loading protocol', 'creatine safety evidence'] },
  { tier: 'ingredient', title: 'Alpha-Lipoic Acid: The Universal Antioxidant for Blood Sugar and Nerve Health', category: 'Supplements', primaryKeyword: 'alpha-lipoic acid supplement', secondaryKeywords: ['ALA blood sugar', 'alpha-lipoic acid neuropathy', 'R-ALA vs S-ALA'] },
  { tier: 'ingredient', title: 'B-Complex Vitamins: Why Getting the Methylated Forms Matters', category: 'Supplements', primaryKeyword: 'B-complex supplement', secondaryKeywords: ['methylated B12', 'methylfolate vs folic acid', 'B vitamins energy'] },
  { tier: 'ingredient', title: 'Iron: Optimal Ferritin Levels, Absorption, and When to Supplement', category: 'Supplements', primaryKeyword: 'iron supplement', secondaryKeywords: ['ferritin levels optimal', 'iron deficiency anaemia', 'iron absorption vitamin C'] },
  { tier: 'ingredient', title: 'Probiotics: Strains, CFU Counts, and the Research Behind Each', category: 'Supplements', primaryKeyword: 'probiotic supplement', secondaryKeywords: ['best probiotic strains', 'Lactobacillus acidophilus', 'probiotic for gut health'] },
  { tier: 'ingredient', title: 'Quercetin: Antihistamine, Anti-Inflammatory, and Senolytic Properties Explained', category: 'Supplements', primaryKeyword: 'quercetin supplement', secondaryKeywords: ['quercetin antihistamine', 'quercetin bioavailability', 'quercetin zinc absorption'] },
  { tier: 'ingredient', title: 'Curcumin and Piperine: Bioavailability, Inflammation, and Brain Health', category: 'Supplements', primaryKeyword: 'curcumin supplement', secondaryKeywords: ['curcumin bioavailability', 'turmeric anti-inflammatory', 'curcumin vs ibuprofen'] },
  { tier: 'ingredient', title: 'Iodine: Thyroid Hormones, Sources, Deficiency, and Safe Supplementation', category: 'Supplements', primaryKeyword: 'iodine supplement', secondaryKeywords: ['iodine thyroid', 'iodine deficiency symptoms', 'kelp vs potassium iodide'] },
  { tier: 'ingredient', title: 'Boron: Testosterone, Bone Density, and the Overlooked Trace Mineral', category: 'Supplements', primaryKeyword: 'boron supplement', secondaryKeywords: ['boron testosterone', 'boron bone health', 'boron mineral deficiency'] },
  { tier: 'ingredient', title: 'Resveratrol: Sirtuin Activation, Cardiovascular Health, and Bioavailability', category: 'Supplements', primaryKeyword: 'resveratrol supplement', secondaryKeywords: ['resveratrol sirtuin', 'trans-resveratrol vs cis', 'resveratrol heart health'] },
  { tier: 'ingredient', title: 'Phosphatidylserine: Memory, Cortisol, and the Clinical Evidence for 100 mg', category: 'Supplements', primaryKeyword: 'phosphatidylserine supplement', secondaryKeywords: ['phosphatidylserine memory', 'phosphatidylserine cortisol', 'brain health phospholipids'] },
  { tier: 'ingredient', title: 'L-Theanine: Calm Focus, Sleep Quality, and the Synergy With Caffeine', category: 'Supplements', primaryKeyword: 'L-theanine supplement', secondaryKeywords: ['L-theanine caffeine stack', 'L-theanine sleep', 'alpha waves L-theanine'] },
  { tier: 'ingredient', title: 'GABA: Natural Sleep Aid or Hype? What the Research Actually Shows', category: 'Supplements', primaryKeyword: 'GABA supplement', secondaryKeywords: ['GABA sleep supplement', 'GABA anxiety relief', 'GABA blood-brain barrier'] },
  { tier: 'ingredient', title: 'Melatonin: Correct Dosing, Jet Lag, and Long-Term Safety', category: 'Supplements', primaryKeyword: 'melatonin supplement', secondaryKeywords: ['melatonin dosage', 'melatonin jet lag', 'melatonin safety concerns'] },
  { tier: 'ingredient', title: 'Magnesium Malate: The Form for Fibromyalgia, Energy, and Muscle Pain', category: 'Supplements', primaryKeyword: 'magnesium malate supplement', secondaryKeywords: ['magnesium for fibromyalgia', 'malic acid supplement', 'magnesium fatigue'] },
  { tier: 'ingredient', title: 'Inositol (Myo-Inositol): PCOS, Insulin Sensitivity, and Mental Health', category: 'Supplements', primaryKeyword: 'inositol supplement', secondaryKeywords: ['myo-inositol PCOS', 'inositol anxiety', 'inositol insulin sensitivity'] },
  { tier: 'ingredient', title: 'Glutamine: Gut Lining, Immune Function, and Recovery After Exercise', category: 'Supplements', primaryKeyword: 'glutamine supplement', secondaryKeywords: ['L-glutamine gut health', 'glutamine leaky gut', 'glutamine immune support'] },
  { tier: 'ingredient', title: 'Spirulina and Chlorella: Detox, Heavy Metals, and Nutritional Density', category: 'Supplements', primaryKeyword: 'spirulina supplement', secondaryKeywords: ['chlorella heavy metal detox', 'spirulina protein', 'algae supplement benefits'] },
  { tier: 'ingredient', title: 'Astragalus Root: Telomere Length, Immunity, and anti-aging Potential', category: 'Supplements', primaryKeyword: 'astragalus supplement', secondaryKeywords: ['astragalus telomere', 'astragalus immune support', 'adaptogen longevity'] },
  { tier: 'ingredient', title: 'Holy Basil (Tulsi): Cortisol, Blood Sugar, and the Adaptogen Evidence', category: 'Supplements', primaryKeyword: 'holy basil supplement', secondaryKeywords: ['tulsi cortisol', 'holy basil adaptogen', 'tulsi blood sugar'] },
  { tier: 'ingredient', title: 'DHEA: Adrenal Hormone, Energy, and When Lab Testing Is Essential', category: 'Supplements', primaryKeyword: 'DHEA supplement', secondaryKeywords: ['DHEA adrenal function', 'DHEA testosterone', 'DHEA age-related decline'] },
  { tier: 'ingredient', title: 'Pregnenolone: The Master Hormone Precursor Most Practitioners Overlook', category: 'Supplements', primaryKeyword: 'pregnenolone supplement', secondaryKeywords: ['pregnenolone memory', 'pregnenolone hormone precursor', 'pregnenolone adrenal'] },
  { tier: 'ingredient', title: 'Pantethine and Pantothenic Acid: Cholesterol, Adrenal Function, and Energy', category: 'Supplements', primaryKeyword: 'pantethine supplement', secondaryKeywords: ['pantothenic acid adrenal', 'B5 cholesterol', 'CoA synthesis pantethine'] },
  { tier: 'ingredient', title: 'Chromium Picolinate: Blood Sugar Regulation and Carbohydrate Craving Research', category: 'Supplements', primaryKeyword: 'chromium picolinate supplement', secondaryKeywords: ['chromium blood sugar', 'chromium insulin sensitivity', 'glucose tolerance factor'] },
  { tier: 'ingredient', title: 'Vanadium: The Trace Mineral for Glucose Metabolism and Bone Density', category: 'Supplements', primaryKeyword: 'vanadium supplement', secondaryKeywords: ['vanadium glucose', 'vanadyl sulphate insulin', 'vanadium bone health'] },
  { tier: 'ingredient', title: 'Electrolytes: Sodium, Potassium, Magnesium — the Ratio That Matters', category: 'Supplements', primaryKeyword: 'electrolyte supplement', secondaryKeywords: ['electrolyte balance', 'sodium potassium ratio', 'hydration electrolytes'] },
  { tier: 'ingredient', title: 'Silica (Silicon Dioxide): Hair, Skin, Nails, and Connective Tissue', category: 'Supplements', primaryKeyword: 'silica supplement', secondaryKeywords: ['silica for hair growth', 'horsetail extract silica', 'silica collagen synthesis'] },
  { tier: 'ingredient', title: 'Hyaluronic Acid: Joints, Skin Hydration, and the Oral Supplementation Evidence', category: 'Supplements', primaryKeyword: 'hyaluronic acid supplement', secondaryKeywords: ['oral hyaluronic acid absorption', 'hyaluronic acid joints', 'skin hydration supplement'] },
  { tier: 'ingredient', title: 'Choline and CDP-Choline: Memory, Liver Health, and the Methyl Donor Cycle', category: 'Supplements', primaryKeyword: 'choline supplement', secondaryKeywords: ['CDP-choline cognition', 'choline liver health', 'acetylcholine production'] },
  { tier: 'ingredient', title: 'Acetyl-L-Carnitine (ALCAR): Brain Health, Neuropathy, and Mitochondrial Support', category: 'Supplements', primaryKeyword: 'acetyl-L-carnitine supplement', secondaryKeywords: ['ALCAR brain health', 'carnitine neuropathy', 'mitochondrial support supplement'] },
  { tier: 'ingredient', title: 'Beta-Glucans: Immune Priming, Cholesterol, and the Different Forms Compared', category: 'Supplements', primaryKeyword: 'beta-glucan supplement', secondaryKeywords: ['oat beta-glucan cholesterol', 'beta-glucan immune modulation', 'yeast beta-glucan'] },
  { tier: 'ingredient', title: 'Pine Bark Extract (Pycnogenol): Endothelial Health, OPCs, and Circulation', category: 'Supplements', primaryKeyword: 'pycnogenol supplement', secondaryKeywords: ['pine bark extract OPC', 'pycnogenol circulation', 'oligomeric proanthocyanidins'] },
  { tier: 'ingredient', title: 'Milk Thistle: Silymarin Bioavailability, Liver Regeneration, and Safe Dosing', category: 'Supplements', primaryKeyword: 'milk thistle supplement', secondaryKeywords: ['silymarin liver', 'milk thistle detox', 'silymarin extraction'] },
  { tier: 'ingredient', title: 'Dandelion Root: Liver Detox, Digestive Bitters, and Diuretic Properties', category: 'Supplements', primaryKeyword: 'dandelion root supplement', secondaryKeywords: ['dandelion liver support', 'dandelion digestive health', 'natural diuretic herbs'] },
  { tier: 'ingredient', title: 'Saw Palmetto: DHT, Prostate Health, and Hair Loss — What the Trials Show', category: 'Supplements', primaryKeyword: 'saw palmetto supplement', secondaryKeywords: ['saw palmetto DHT', 'saw palmetto prostate', 'saw palmetto hair loss'] },
  { tier: 'ingredient', title: '5-HTP: Serotonin, Mood, Weight, and the Safety Considerations', category: 'Supplements', primaryKeyword: '5-HTP supplement', secondaryKeywords: ['5-HTP serotonin', '5-HTP depression', '5-HTP sleep supplement'] },
  { tier: 'ingredient', title: 'Tryptophan: The Amino Acid Precursor to Serotonin and Melatonin', category: 'Supplements', primaryKeyword: 'tryptophan supplement', secondaryKeywords: ['L-tryptophan mood', 'tryptophan melatonin', 'tryptophan vs 5-HTP'] },
  { tier: 'ingredient', title: 'Maca Root: Libido, Energy, Hormone Balance, and the Adaptogen Evidence', category: 'Supplements', primaryKeyword: 'maca root supplement', secondaryKeywords: ['maca libido', 'maca energy', 'maca menopause symptoms'] },
  { tier: 'ingredient', title: 'Fenugreek: Testosterone, Blood Sugar, and Lactation — The Clinical Picture', category: 'Supplements', primaryKeyword: 'fenugreek supplement', secondaryKeywords: ['fenugreek testosterone', 'fenugreek blood sugar', 'fenugreek breastfeeding'] },
  { tier: 'ingredient', title: 'Tribulus Terrestris: Testosterone Claims vs Reality — An Evidence Review', category: 'Supplements', primaryKeyword: 'tribulus terrestris supplement', secondaryKeywords: ['tribulus testosterone research', 'tribulus libido', 'tribulus steroidal saponins'] },
  { tier: 'ingredient', title: 'Morinda Root (Noni): Antioxidants, Nitric Oxide, and the Supplement Evidence', category: 'Supplements', primaryKeyword: 'morinda root supplement', secondaryKeywords: ['noni antioxidant', 'morinda nitric oxide', 'noni juice supplement'] },
  { tier: 'ingredient', title: 'Valerian Root: Sleep Latency, GABA, and What Meta-Analyses Conclude', category: 'Supplements', primaryKeyword: 'valerian root supplement', secondaryKeywords: ['valerian sleep', 'valerian GABA', 'valerian anxiety supplement'] },
  { tier: 'ingredient', title: 'Passionflower: Anxiety, Insomnia, and the Flavonoid Mechanism', category: 'Supplements', primaryKeyword: 'passionflower supplement', secondaryKeywords: ['passionflower anxiety', 'passionflower sleep', 'chrysin passionflower'] },
  { tier: 'ingredient', title: "Schisandra Berry: Liver Adaptogen, Stress Resilience, and Athletic Performance", category: 'Supplements', primaryKeyword: 'schisandra supplement', secondaryKeywords: ['schisandra liver', 'schisandra adaptogen', 'schisandra athletic performance'] },
  { tier: 'ingredient', title: 'Mucuna Pruriens: L-DOPA, Dopamine, Testosterone, and the Research', category: 'Supplements', primaryKeyword: 'mucuna pruriens supplement', secondaryKeywords: ['mucuna L-DOPA', 'mucuna dopamine', 'mucuna testosterone'] },
  { tier: 'ingredient', title: 'Eleuthero (Siberian Ginseng): Adaptogen Endurance and Immune Evidence', category: 'Supplements', primaryKeyword: 'eleuthero supplement', secondaryKeywords: ['Siberian ginseng adaptogen', 'eleuthero endurance', 'eleuthero immune function'] },
  { tier: 'ingredient', title: 'Korean Ginseng (Panax): Energy, Immunity, and Cognitive Performance', category: 'Supplements', primaryKeyword: 'Korean red ginseng supplement', secondaryKeywords: ['panax ginseng cognitive', 'ginseng energy', 'ginsenoside mechanism'] },
  { tier: 'ingredient', title: 'Ginkgo Biloba: Memory, Blood Flow, and the Correct Standardised Extract', category: 'Supplements', primaryKeyword: 'ginkgo biloba supplement', secondaryKeywords: ['ginkgo memory', 'ginkgo blood circulation', 'ginkgo biloba EGb 761'] },
  { tier: 'ingredient', title: 'Black Seed Oil (Nigella Sativa): The Anti-Inflammatory Seed Backed by 1,000 Studies', category: 'Supplements', primaryKeyword: 'black seed oil supplement', secondaryKeywords: ['nigella sativa thymoquinone', 'black seed oil inflammation', 'black seed oil immune'] },
  { tier: 'ingredient', title: 'Coenzyme Q10 for Fertility: Egg Quality, Mitochondrial Health, and Dosing Protocol', category: 'Supplements', primaryKeyword: 'CoQ10 fertility', secondaryKeywords: ['CoQ10 egg quality', 'CoQ10 sperm health', 'mitochondria fertility'] },
  { tier: 'ingredient', title: 'Fish Oil vs Algae Oil: Which Omega-3 Source Is Superior?', category: 'Supplements', primaryKeyword: 'fish oil vs algae oil', secondaryKeywords: ['vegan omega-3', 'DHA algae oil', 'sustainable omega-3 source'] },

  // ── COMPARISONS ───────────────────────────────────────────────────────────
  { tier: 'comparison', title: 'Ones vs Viome: AI-Driven Supplement Formulas vs Gut Microbiome Testing', category: 'Comparisons', primaryKeyword: 'Ones vs Viome supplements', secondaryKeywords: ['Viome review personalized supplements', 'gut microbiome supplement recommendations', 'AI health platform comparison'] },
  { tier: 'comparison', title: 'Ones vs Ritual: Lab-Tested Custom Formulas vs One-Size Multivitamins', category: 'Comparisons', primaryKeyword: 'Ones vs Ritual supplements', secondaryKeywords: ['Ritual vitamins review', 'personalized vs generic supplements', 'multivitamin comparison'] },
  { tier: 'comparison', title: 'Ones vs Thorne: AI-Driven Formulas vs Practitioner-Grade Supplements', category: 'Comparisons', primaryKeyword: 'Ones vs Thorne supplements', secondaryKeywords: ['Thorne supplements review', 'practitioner supplements personalized', 'custom formula vs off-the-shelf'] },
  { tier: 'comparison', title: 'Ones vs Function Health: Which Platform Uses Your Lab Data Better?', category: 'Comparisons', primaryKeyword: 'personalized supplement brands comparison', secondaryKeywords: ['AI supplement platform', 'blood test supplement service', 'supplement subscription review'] },
  { tier: 'comparison', title: 'Magnesium Glycinate vs Citrate vs Oxide: Which Form Should You Take?', category: 'Supplements', primaryKeyword: 'best form of magnesium', secondaryKeywords: ['magnesium glycinate vs citrate', 'magnesium oxide bioavailability', 'magnesium supplement comparison'] },
  { tier: 'comparison', title: 'Zinc Picolinate vs Zinc Gluconate vs Zinc Bisglycinate: Form Matters More Than Dose', category: 'Supplements', primaryKeyword: 'best form of zinc supplement', secondaryKeywords: ['zinc picolinate absorption', 'zinc bisglycinate immune', 'zinc supplement comparison'] },
  { tier: 'comparison', title: 'Vitamin D2 vs D3: Why Cholecalciferol Is the Clear Winner', category: 'Supplements', primaryKeyword: 'vitamin D2 vs D3', secondaryKeywords: ['cholecalciferol vs ergocalciferol', 'vitamin D3 absorption', 'vitamin D supplement form'] },
  { tier: 'comparison', title: 'Whey vs Plant Protein: A Head-to-Head on Amino Acids and Digestion', category: 'Supplements', primaryKeyword: 'whey vs plant protein', secondaryKeywords: ['pea protein vs whey', 'complete protein plant-based', 'protein supplement comparison'] },
  { tier: 'comparison', title: 'NMN vs NR: Which NAD+ Precursor Is More Effective?', category: 'Supplements', primaryKeyword: 'NMN vs NR supplement', secondaryKeywords: ['NAD+ precursor comparison', 'nicotinamide riboside NR', 'NMN bioavailability'] },
  { tier: 'comparison', title: 'Ubiquinone vs Ubiquinol: Which Form of CoQ10 Do You Actually Need?', category: 'Supplements', primaryKeyword: 'ubiquinone vs ubiquinol', secondaryKeywords: ['CoQ10 form comparison', 'ubiquinol absorption over 40', 'active form CoQ10'] },
  { tier: 'comparison', title: 'Methylfolate vs Folic Acid: Why the MTHFR Gene Changes Everything', category: 'Supplements', primaryKeyword: 'methylfolate vs folic acid', secondaryKeywords: ['MTHFR mutation supplement', 'methylated folate', '5-MTHF vs folic acid'] },
  { tier: 'comparison', title: 'Melatonin vs Magnesium for Sleep: Which Works Better and When to Use Both', category: 'Supplements', primaryKeyword: 'melatonin vs magnesium for sleep', secondaryKeywords: ['best sleep supplement comparison', 'magnesium glycinate sleep', 'melatonin dosage sleep'] },
  { tier: 'comparison', title: 'Berberine vs Metformin: The Diabetes Drug Comparison That Surprised Researchers', category: 'Comparisons', primaryKeyword: 'berberine vs metformin', secondaryKeywords: ['berberine blood sugar research', 'metformin alternative supplement', 'natural metformin'] },
  { tier: 'comparison', title: 'Turmeric/Curcumin vs Ibuprofen for Inflammation: What the Research Shows', category: 'Comparisons', primaryKeyword: 'curcumin vs ibuprofen inflammation', secondaryKeywords: ['natural anti-inflammatory supplement', 'curcumin pain relief', 'NSAID alternative natural'] },
  { tier: 'comparison', title: 'Ashwagandha vs Rhodiola: Which Adaptogen Is Right for Your Stress Profile?', category: 'Comparisons', primaryKeyword: 'ashwagandha vs rhodiola', secondaryKeywords: ['best adaptogen for stress', 'ashwagandha rhodiola comparison', 'cortisol adaptogen'] },
  { tier: 'comparison', title: 'Collagen vs Bone Broth: Which Source of Peptides Is More Bioavailable?', category: 'Comparisons', primaryKeyword: 'collagen vs bone broth', secondaryKeywords: ['hydrolysed collagen absorption', 'bone broth collagen peptides', 'collagen supplement vs food'] },
  { tier: 'comparison', title: 'Lion\'s Mane vs Reishi vs Cordyceps: The Mushroom Supplement Guide', category: 'Comparisons', primaryKeyword: 'mushroom supplement comparison', secondaryKeywords: ['lion\'s mane vs reishi', 'cordyceps energy supplement', 'functional mushroom stack'] },
  { tier: 'comparison', title: 'Liposomal vs Standard Vitamin C: Is the Price Premium Worth It?', category: 'Comparisons', primaryKeyword: 'liposomal vitamin C vs standard', secondaryKeywords: ['vitamin C bioavailability', 'liposomal supplement absorption', 'high-dose vitamin C form'] },
  { tier: 'comparison', title: 'Krill Oil vs Fish Oil: Phospholipid Omega-3 vs Triglyceride Form', category: 'Comparisons', primaryKeyword: 'krill oil vs fish oil', secondaryKeywords: ['krill oil phospholipids', 'omega-3 absorption comparison', 'astaxanthin krill oil'] },
  { tier: 'comparison', title: 'Probiotic Capsules vs Fermented Foods: What Science Says About Gut Colonisation', category: 'Comparisons', primaryKeyword: 'probiotic supplements vs fermented foods', secondaryKeywords: ['probiotic colonisation evidence', 'kefir vs probiotic capsule', 'gut microbiome supplement'] },

  // ── SYMPTOMS ──────────────────────────────────────────────────────────────
  { tier: 'symptom', title: 'Chronic Fatigue: Root Causes, Blood Markers to Check, and the Supplement Protocol', category: 'Symptoms', primaryKeyword: 'chronic fatigue supplements', secondaryKeywords: ['fatigue root causes', 'adrenal fatigue lab tests', 'iron ferritin fatigue'] },
  { tier: 'symptom', title: 'Brain Fog: What\'s Causing It and the Nutritional Protocol to Clear It', category: 'Symptoms', primaryKeyword: 'brain fog supplements', secondaryKeywords: ['brain fog causes', 'inflammation brain fog', 'cognitive clarity supplement'] },
  { tier: 'symptom', title: 'Poor Sleep: The Hormonal, Nutritional, and Lifestyle Drivers and How to Fix Them', category: 'Symptoms', primaryKeyword: 'poor sleep supplements', secondaryKeywords: ['sleep quality supplements', 'cortisol and sleep', 'magnesium for sleep'] },
  { tier: 'symptom', title: 'Anxiety: Evidence-Based Supplements That Actually Calm the Nervous System', category: 'Symptoms', primaryKeyword: 'supplements for anxiety', secondaryKeywords: ['magnesium anxiety', 'ashwagandha anxiety', 'L-theanine stress relief'] },
  { tier: 'symptom', title: 'Low Energy in the Morning: Cortisol Awakening Response and Adrenal Health', category: 'Symptoms', primaryKeyword: 'low morning energy supplements', secondaryKeywords: ['cortisol awakening response', 'adrenal support morning', 'low cortisol morning'] },
  { tier: 'symptom', title: 'Hair Loss in Women: Ferritin, Thyroid, DHEA, and the Nutritional Solutions', category: 'Symptoms', primaryKeyword: 'supplements for hair loss women', secondaryKeywords: ['ferritin hair loss', 'thyroid hair loss female', 'biotin vs iron hair loss'] },
  { tier: 'symptom', title: 'Muscle Cramps and Spasms: The Electrolyte and Mineral Deficiencies Behind Them', category: 'Symptoms', primaryKeyword: 'supplements for muscle cramps', secondaryKeywords: ['magnesium muscle cramps', 'potassium deficiency cramps', 'electrolyte muscle spasms'] },
  { tier: 'symptom', title: 'Low Libido: The Hormonal, Nutritional, and Stress Drivers for Men and Women', category: 'Symptoms', primaryKeyword: 'low libido supplements', secondaryKeywords: ['testosterone and libido', 'maca libido supplement', 'zinc testosterone libido'] },
  { tier: 'symptom', title: 'Slow Recovery After Exercise: The Nutrition and Supplement Protocol', category: 'Symptoms', primaryKeyword: 'recovery supplements exercise', secondaryKeywords: ['post-workout recovery nutrition', 'collagen exercise recovery', 'magnesium post-exercise'] },
  { tier: 'symptom', title: 'Frequent Illness: Why Your Immune System Is Underperforming and How to Fix It', category: 'Symptoms', primaryKeyword: 'immune support supplements frequent illness', secondaryKeywords: ['vitamin D immunity', 'zinc immune function', 'adaptogen immune health'] },
  { tier: 'symptom', title: 'Digestive Issues: Bloating, IBS, and the Supplement and Diet Protocol', category: 'Symptoms', primaryKeyword: 'supplements for bloating digestion', secondaryKeywords: ['IBS supplement protocol', 'gut health bloating', 'digestive enzymes probiotic'] },
  { tier: 'symptom', title: 'Mood Swings and Irritability: Hormonal and Nutritional Root Causes', category: 'Symptoms', primaryKeyword: 'supplements for mood swings', secondaryKeywords: ['PMS mood supplement', 'serotonin mood support', 'magnesium PMS irritability'] },
  { tier: 'symptom', title: 'Afternoon Energy Crash: Blood Sugar, Cortisol, and the Nutritional Fix', category: 'Symptoms', primaryKeyword: 'afternoon energy crash supplements', secondaryKeywords: ['blood sugar energy crash', 'berberine afternoon energy', 'chromium insulin sensitivity'] },
  { tier: 'symptom', title: 'Joint Pain and Stiffness: The Anti-Inflammatory Supplement Stack', category: 'Symptoms', primaryKeyword: 'supplements for joint pain', secondaryKeywords: ['glucosamine joint health', 'curcumin joint pain', 'omega-3 inflammation joints'] },
  { tier: 'symptom', title: 'Dry Skin and Hair: Nutritional Deficiencies Behind Poor Skin Barrier Function', category: 'Symptoms', primaryKeyword: 'supplements for dry skin', secondaryKeywords: ['omega-3 skin hydration', 'biotin skin hair', 'collagen skin barrier'] },
  { tier: 'symptom', title: 'Headaches and Migraines: The Magnesium, Riboflavin, and CoQ10 Evidence', category: 'Symptoms', primaryKeyword: 'supplements for migraines', secondaryKeywords: ['magnesium migraine prevention', 'riboflavin B2 headache', 'CoQ10 migraine research'] },
  { tier: 'symptom', title: 'Poor Concentration at Work: Nootropics, Diet, and Lifestyle Fixes', category: 'Symptoms', primaryKeyword: 'supplements for concentration work', secondaryKeywords: ['focus supplement adults', 'lion\'s mane focus', 'phosphatidylserine concentration'] },
  { tier: 'symptom', title: 'Constipation: Fiber, Magnesium, and the Gut Motility Protocol', category: 'Symptoms', primaryKeyword: 'supplements for constipation', secondaryKeywords: ['magnesium constipation', 'psyllium husk constipation', 'gut motility supplement'] },
  { tier: 'symptom', title: 'Night Sweats: Hormonal Causes, Lab Markers, and Natural Interventions', category: 'Symptoms', primaryKeyword: 'night sweats natural remedies', secondaryKeywords: ['menopause night sweats supplement', 'cortisol night sweats', 'sage night sweats'] },
  { tier: 'symptom', title: 'Low Mood in Winter: SAD, Vitamin D, Light Therapy, and the Full Protocol', category: 'Symptoms', primaryKeyword: 'seasonal depression supplements', secondaryKeywords: ['vitamin D winter depression', 'SAD light therapy supplement', 'serotonin winter mood'] },
  { tier: 'symptom', title: 'Slow Metabolism: Lab Testing, Thyroid Function, and Metabolic Support Supplements', category: 'Symptoms', primaryKeyword: 'slow metabolism supplements', secondaryKeywords: ['thyroid metabolism', 'metabolic rate supplement', 'B-vitamins metabolism'] },
  { tier: 'symptom', title: 'Hormonal Acne in Adults: The Zinc, Inositol, and Blood Sugar Connection', category: 'Symptoms', primaryKeyword: 'supplements for hormonal acne', secondaryKeywords: ['zinc acne supplement', 'inositol PCOS acne', 'blood sugar and acne breakouts'] },
  { tier: 'symptom', title: 'Stress Eating and Sugar Cravings: Chromium, GABA, and the Neurochemical Drivers', category: 'Symptoms', primaryKeyword: 'supplements for sugar cravings', secondaryKeywords: ['chromium sugar cravings', 'GABA stress eating', 'serotonin food cravings'] },
  { tier: 'symptom', title: 'Weak Nails and Brittle Hair: Silica, Biotin, and Keratin Nutrition', category: 'Symptoms', primaryKeyword: 'supplements for weak nails', secondaryKeywords: ['biotin nail growth', 'silica nail strength', 'collagen hair nails'] },
  { tier: 'symptom', title: 'Poor Memory and Recall: Cholinergic Nutrients and the Brain-Health Protocol', category: 'Symptoms', primaryKeyword: 'supplements for memory and recall', secondaryKeywords: ['choline memory supplement', 'bacopa memory', 'lion\'s mane neurogenesis'] },
  { tier: 'symptom', title: 'Exercise Intolerance and Breathlessness: Iron, B12, and the Oxygen Delivery Chain', category: 'Symptoms', primaryKeyword: 'exercise intolerance supplements', secondaryKeywords: ['iron exercise performance', 'B12 anaemia exercise', 'oxygen delivery nutrients'] },

  // ── LAB MARKERS ───────────────────────────────────────────────────────────
  { tier: 'lab', title: 'Ferritin Lab Test: Optimal Ranges, What Low Ferritin Means, and How to Fix It', category: 'Lab Results', primaryKeyword: 'optimal ferritin levels', secondaryKeywords: ['ferritin deficiency symptoms', 'ferritin supplement protocol', 'iron stores blood test'] },
  { tier: 'lab', title: 'Vitamin D Blood Test: What Optimal Looks Like and Why 20 ng/mL Isn\'t Enough', category: 'Lab Results', primaryKeyword: 'vitamin D blood test optimal range', secondaryKeywords: ['25-OH vitamin D levels', 'vitamin D deficiency threshold', 'vitamin D lab test interpretation'] },
  { tier: 'lab', title: 'TSH, T3, and T4: Understanding Your Full Thyroid Panel Beyond the Standard Test', category: 'Lab Results', primaryKeyword: 'thyroid blood test interpretation', secondaryKeywords: ['TSH optimal range', 'free T3 T4 blood test', 'thyroid panel comprehensive'] },
  { tier: 'lab', title: 'hs-CRP: The Inflammation Marker That Predicts Heart Disease Before Symptoms Appear', category: 'Lab Results', primaryKeyword: 'hs-CRP blood test', secondaryKeywords: ['C-reactive protein inflammation', 'hsCRP cardiovascular risk', 'reduce CRP supplements'] },
  { tier: 'lab', title: 'HbA1c and Fasting Glucose: Your Complete Guide to Blood Sugar Markers', category: 'Lab Results', primaryKeyword: 'HbA1c blood test interpretation', secondaryKeywords: ['fasting glucose optimal range', 'pre-diabetic HbA1c', 'blood sugar markers explained'] },
  { tier: 'lab', title: 'Homocysteine: The Cardiovascular Risk Marker Hidden in Plain Sight', category: 'Lab Results', primaryKeyword: 'homocysteine blood test', secondaryKeywords: ['high homocysteine causes', 'B vitamins homocysteine', 'homocysteine heart disease risk'] },
  { tier: 'lab', title: 'DHEA-S Blood Test: Adrenal Reserve, aging, and What Your Levels Mean', category: 'Lab Results', primaryKeyword: 'DHEA-S blood test', secondaryKeywords: ['DHEA adrenal reserve', 'DHEA-S decline with age', 'adrenal function lab markers'] },
  { tier: 'lab', title: 'Cortisol Lab Testing: Saliva, Blood, and Urine — Which Test Is Most Useful?', category: 'Lab Results', primaryKeyword: 'cortisol testing methods', secondaryKeywords: ['saliva cortisol test', 'DUTCH cortisol test', 'adrenal function lab testing'] },
  { tier: 'lab', title: 'Complete Blood Count (CBC): What Every Marker Means and the Optimal Ranges', category: 'Lab Results', primaryKeyword: 'complete blood count interpretation', secondaryKeywords: ['CBC blood test markers', 'haematocrit optimal', 'white blood cell count normal'] },
  { tier: 'lab', title: 'Lipid Panel Explained: LDL Particle Size, HDL, Triglycerides, and ApoB', category: 'Lab Results', primaryKeyword: 'lipid panel interpretation', secondaryKeywords: ['LDL particle size test', 'ApoB cardiovascular risk', 'HDL cholesterol optimal'] },
  { tier: 'lab', title: 'Insulin: Why Fasting Insulin Is More Useful Than Glucose for Metabolic Health', category: 'Lab Results', primaryKeyword: 'fasting insulin blood test', secondaryKeywords: ['insulin resistance lab test', 'HOMA-IR calculation', 'optimal fasting insulin level'] },
  { tier: 'lab', title: 'Omega-3 Index: The Blood Test That Reveals Your Heart Disease Risk', category: 'Lab Results', primaryKeyword: 'omega-3 index test', secondaryKeywords: ['EPA DHA blood test', 'omega-3 index optimal range', 'omega-3 blood test heart risk'] },
  { tier: 'lab', title: 'Testosterone Total vs Free: Which Measurement Actually Matters?', category: 'Lab Results', primaryKeyword: 'testosterone blood test men', secondaryKeywords: ['free testosterone vs total', 'SHBG testosterone binding', 'testosterone lab interpretation'] },
  { tier: 'lab', title: 'Oestradiol and Progesterone: Understanding the Female Hormone Panel', category: 'Lab Results', primaryKeyword: 'oestradiol progesterone blood test', secondaryKeywords: ['female hormone panel', 'oestrogen progesterone ratio', 'hormone blood test women'] },
  { tier: 'lab', title: 'Magnesium Red Blood Cell Test: Why Serum Magnesium Misses the Point', category: 'Lab Results', primaryKeyword: 'magnesium RBC test', secondaryKeywords: ['RBC magnesium vs serum', 'intracellular magnesium test', 'magnesium deficiency blood test'] },
  { tier: 'lab', title: 'B12 and Methylmalonic Acid: Getting a True Picture of Vitamin B12 Status', category: 'Lab Results', primaryKeyword: 'vitamin B12 blood test optimal', secondaryKeywords: ['methylmalonic acid B12', 'active B12 holotranscobalamin', 'B12 deficiency lab test'] },
  { tier: 'lab', title: 'Folate and MTHFR: The Gene-Nutrient Interaction That Affects Millions', category: 'Lab Results', primaryKeyword: 'MTHFR gene test', secondaryKeywords: ['folate blood test MTHFR', 'methylfolate MTHFR variant', 'homocysteine MTHFR'] },
  { tier: 'lab', title: 'GGT and Liver Enzymes: What ALT, AST, and GGT Tell You About Liver Health', category: 'Lab Results', primaryKeyword: 'liver enzyme blood test', secondaryKeywords: ['ALT AST elevated causes', 'GGT alcohol marker', 'liver function blood test'] },
  { tier: 'lab', title: 'eGFR and Creatinine: Monitoring Kidney Function Through Lab Tests', category: 'Lab Results', primaryKeyword: 'kidney function blood test', secondaryKeywords: ['eGFR creatinine levels', 'kidney health markers', 'creatinine optimal range'] },
  { tier: 'lab', title: 'Zinc Plasma Test: Assessing Levels, Copper Competition, and the Right Ratio', category: 'Lab Results', primaryKeyword: 'zinc plasma blood test', secondaryKeywords: ['zinc copper ratio', 'zinc deficiency test', 'plasma zinc level optimal'] },
  { tier: 'lab', title: 'Testosterone in Women: When to Test and the Signs of Androgen Imbalance', category: 'Lab Results', primaryKeyword: 'testosterone women blood test', secondaryKeywords: ['free testosterone women', 'androgen excess women', 'PCOS testosterone levels'] },
  { tier: 'lab', title: 'LH and FSH: The Pituitary Hormones That Govern Reproductive Health', category: 'Lab Results', primaryKeyword: 'LH FSH blood test', secondaryKeywords: ['LH FSH ratio PCOS', 'FSH menopause marker', 'pituitary hormones fertility'] },

  // ── LIFESTYLE ─────────────────────────────────────────────────────────────
  { tier: 'lifestyle', title: 'Cold Exposure and Supplements: How to Enhance the Benefits of Cold Therapy', category: 'Biohacking', primaryKeyword: 'cold therapy supplements', secondaryKeywords: ['cold plunge benefits', 'brown fat supplements cold', 'ice bath recovery protocol'] },
  { tier: 'lifestyle', title: 'Intermittent Fasting and Supplements: What to Take, When, and Why', category: 'Lifestyle', primaryKeyword: 'supplements for intermittent fasting', secondaryKeywords: ['IF supplement timing', 'fasting electrolytes', 'NAD+ fasting synergy'] },
  { tier: 'lifestyle', title: 'The Supplement Stack for High-Stress Professionals and Executives', category: 'Lifestyle', primaryKeyword: 'supplement stack for stress', secondaryKeywords: ['executive health protocol', 'high performer supplements', 'cortisol management stack'] },
  { tier: 'lifestyle', title: 'Vegetarian and Vegan Supplement Gaps: The Complete Checklist', category: 'Lifestyle', primaryKeyword: 'vegan supplement stack', secondaryKeywords: ['vegetarian B12 supplement', 'vegan omega-3 algae', 'plant-based iron supplement'] },
  { tier: 'lifestyle', title: 'Supplements for Endurance Athletes: The Evidence-Based Performance Stack', category: 'Lifestyle', primaryKeyword: 'endurance athlete supplements', secondaryKeywords: ['marathon runner supplement protocol', 'iron athlete supplement', 'CoQ10 endurance'] },
  { tier: 'lifestyle', title: 'Strength Training and Supplement Timing: The Window That Really Matters', category: 'Lifestyle', primaryKeyword: 'strength training supplements timing', secondaryKeywords: ['creatine timing strength', 'protein post-workout window', 'magnesium strength training'] },
  { tier: 'lifestyle', title: 'Supplements for Shift Workers: Managing Circadian Disruption Nutritionally', category: 'Lifestyle', primaryKeyword: 'supplements for shift workers', secondaryKeywords: ['circadian rhythm supplement', 'melatonin shift work', 'shift worker health protocol'] },
  { tier: 'lifestyle', title: 'Supplements by Age: What Changes Nutritionally in Your 30s, 40s, 50s, and Beyond', category: 'Lifestyle', primaryKeyword: 'supplements by age decade', secondaryKeywords: ['supplements in your 40s', 'aging nutritional needs', 'supplement stack over 50'] },
  { tier: 'lifestyle', title: 'Alcohol and Supplements: Depletion, Liver Support, and Recovery', category: 'Lifestyle', primaryKeyword: 'supplements for alcohol drinkers', secondaryKeywords: ['alcohol nutrient depletion', 'liver supplements alcohol', 'B-vitamins alcohol metabolism'] },
  { tier: 'lifestyle', title: 'Travel and Supplement Protocol: Jet Lag, Immunity, and Staying on Track', category: 'Lifestyle', primaryKeyword: 'travel supplement protocol', secondaryKeywords: ['jet lag supplement', 'travel immune support', 'melatonin jet lag timing'] },
  { tier: 'lifestyle', title: 'Supplements During Pregnancy: Safe Choices and What to Avoid', category: 'Lifestyle', primaryKeyword: 'pregnancy supplements safe', secondaryKeywords: ['prenatal supplement protocol', 'folate pregnancy', 'DHA pregnancy supplement'] },
  { tier: 'lifestyle', title: 'Postpartum Nutrition: The Supplement Protocol for Recovery and Milk Production', category: 'Lifestyle', primaryKeyword: 'postpartum supplements', secondaryKeywords: ['breastfeeding vitamins', 'postnatal supplement protocol', 'iron postpartum'] },
  { tier: 'lifestyle', title: 'Perimenopause Supplement Protocol: Managing the Transition Naturally', category: 'Lifestyle', primaryKeyword: 'perimenopause supplements', secondaryKeywords: ['menopause supplement protocol', 'black cohosh perimenopause', 'magnesium perimenopause symptoms'] },
  { tier: 'lifestyle', title: 'Caffeine Dependence and Adrenal Health: How to Reset Your Energy System', category: 'Lifestyle', primaryKeyword: 'caffeine dependence adrenal health', secondaryKeywords: ['caffeine withdrawal supplements', 'adrenal reset protocol', 'energy without caffeine'] },
  { tier: 'lifestyle', title: 'Sleep Chronotypes and Supplement Timing: Are You a Lion, Bear, or Wolf?', category: 'Lifestyle', primaryKeyword: 'sleep chronotype supplement timing', secondaryKeywords: ['circadian supplement schedule', 'chronotype melatonin timing', 'sleep type health protocol'] },
  { tier: 'lifestyle', title: 'High Altitude Training and Supplements: Iron, EPO, and the Evidence', category: 'Lifestyle', primaryKeyword: 'altitude training supplements', secondaryKeywords: ['altitude iron supplement', 'EPO iron altitude', 'respiratory supplement altitude'] },
  { tier: 'lifestyle', title: 'Sauna Use and Supplement Synergies: Heat Shock Proteins and Recovery', category: 'Lifestyle', primaryKeyword: 'sauna supplement protocol', secondaryKeywords: ['sauna heat shock proteins', 'electrolytes sauna', 'infrared sauna supplement stack'] },
  { tier: 'lifestyle', title: 'Plant-Based Athletes: Closing the Nutritional Gaps for Performance', category: 'Lifestyle', primaryKeyword: 'plant-based athlete supplements', secondaryKeywords: ['vegan athlete nutrition', 'creatine vegan athletes', 'iron vegan athlete supplement'] },
  { tier: 'lifestyle', title: 'Over 60 and Supplementing: The Senior Nutrient Gaps Most GPs Miss', category: 'Lifestyle', primaryKeyword: 'supplements for over 60', secondaryKeywords: ['elderly supplement needs', 'vitamin B12 absorption elderly', 'calcium vitamin D seniors'] },
  { tier: 'lifestyle', title: 'Keto Diet and Supplements: Electrolytes, Micronutrients, and What You Deplete', category: 'Lifestyle', primaryKeyword: 'keto diet supplement protocol', secondaryKeywords: ['ketogenic electrolytes', 'keto magnesium supplement', 'nutrient depletion keto'] },

  // ── HIGH-OPPORTUNITY INGREDIENT CLUSTERS (data-backed: DataForSEO) ────────

  // Score 201,000 — 201K vol, KD 1
  { tier: 'ingredient', title: 'Creatine Monohydrate Supplement: The Complete Evidence-Based Guide', category: 'Supplements', primaryKeyword: 'creatine monohydrate supplement', secondaryKeywords: ['creatine monohydrate dosage', 'creatine monohydrate for weight loss', 'creatine loading protocol', 'best creatine monohydrate', 'creatine monohydrate benefits'] },

  // Score 60,200 — 301K vol, KD 5
  { tier: 'ingredient', title: 'Magnesium Glycinate Supplement: Why Doctors Call It the Best Absorbed Form', category: 'Supplements', primaryKeyword: 'magnesium glycinate supplement', secondaryKeywords: ['magnesium glycinate vs citrate', 'magnesium glycinate benefits', 'magnesium glycinate dosage', 'best magnesium supplement', 'magnesium glycinate side effects'] },

  // Score 20,625 — 165K vol, KD 8
  { tier: 'ingredient', title: 'Vitamin D3 Supplement: Optimal Dosage, Blood Levels, and K2 Synergy', category: 'Supplements', primaryKeyword: 'vitamin d3 supplement', secondaryKeywords: ['vitamin D3 K2 supplement', 'vitamin D deficiency', 'optimal vitamin D level', 'vitamin D3 dosage', 'vitamin d3 side effects'] },

  // Score 15,375 — 246K vol, KD 16
  { tier: 'ingredient', title: 'Magnesium Glycinate for Sleep: Clinical Dosing, Timing, and Evidence', category: 'Sleep', primaryKeyword: 'magnesium glycinate for sleep', secondaryKeywords: ['magnesium glycinate sleep dosage', 'magnesium for insomnia', 'best magnesium for sleep', 'magnesium sleep timing', 'magnesium glycinate anxiety sleep'] },

  // Score 8,222 — 74K vol, KD 9
  { tier: 'ingredient', title: 'Magnesium Citrate vs Glycinate: Which Form Is Right for You?', category: 'Supplements', primaryKeyword: 'magnesium citrate supplement', secondaryKeywords: ['magnesium citrate vs glycinate', 'magnesium citrate benefits', 'magnesium citrate dosage', 'magnesium citrate side effects', 'types of magnesium'] },

  // Score 8,100 — 8.1K vol, KD 1
  { tier: 'ingredient', title: 'Vitamin C Deficiency Symptoms: Early Signs, Risk Factors, and Solutions', category: 'Vitamins', primaryKeyword: 'vitamin c deficiency symptoms', secondaryKeywords: ['signs of vitamin C deficiency', 'scurvy early symptoms', 'how much vitamin C per day', 'vitamin C deficiency causes', 'vitamin C blood test'] },

  // Score 6,346 — 165K vol, KD 26
  { tier: 'ingredient', title: 'Vitamin C Supplement: Ascorbic Acid vs Liposomal — Does Form Matter?', category: 'Vitamins', primaryKeyword: 'vitamin c supplement', secondaryKeywords: ['liposomal vitamin C vs ascorbic acid', 'vitamin C benefits', 'vitamin C dosage', 'vitamin C immune support', 'vitamin c side effects'] },

  // Score 6,188 — 49.5K vol, KD 8
  { tier: 'ingredient', title: 'Collagen Peptides Supplement: Skin, Joints, and Gut — What the Research Says', category: 'Supplements', primaryKeyword: 'collagen peptides supplement', secondaryKeywords: ['collagen peptides benefits', 'collagen peptides side effects', 'hydrolyzed collagen supplement', 'marine vs bovine collagen', 'collagen supplement dosage'] },

  // Score 5,517 — 33.1K vol, KD 6
  { tier: 'ingredient', title: 'Psyllium Husk Supplement: Dosing, Benefits, and Why Timing Matters', category: 'Gut Health', primaryKeyword: 'psyllium husk fiber supplement', secondaryKeywords: ['psyllium husk benefits', 'psyllium husk dosage', 'psyllium husk for cholesterol', 'psyllium husk constipation', 'fiber supplement for gut health'] },

  // Score 4,654 — 60.5K vol, KD 13
  { tier: 'ingredient', title: "Lion's Mane Mushroom Supplement: Nerve Growth Factor and Cognitive Benefits", category: 'Brain Health', primaryKeyword: "lion's mane mushroom supplement", secondaryKeywords: ["lion's mane benefits", "lion's mane dosage", "lion's mane for anxiety", "lion's mane neurogenesis", "functional mushroom cognitive support"] },

  // Score 4,033 — 60.5K vol, KD 15
  { tier: 'ingredient', title: 'Vitamin D3 and K2 Together: Why This Combination Changes Everything', category: 'Vitamins', primaryKeyword: 'vitamin D3 K2 supplement', secondaryKeywords: ['vitamin D3 K2 MK-7 dosage', 'K2 prevents arterial calcification', 'vitamin D toxicity K2', 'best D3 K2 supplement', 'vitamin D K2 bones'] },

  // Score 3,700 — 22.2K vol, KD 6
  { tier: 'ingredient', title: 'Zinc Deficiency Symptoms: The Blood Test Every Immune-Focused Person Should Know', category: 'Minerals', primaryKeyword: 'zinc deficiency symptoms', secondaryKeywords: ['signs of zinc deficiency', 'zinc deficiency immune system', 'zinc serum test', 'zinc bisglycinate supplement', 'zinc deficiency hair loss'] },

  // Score 3,300 — 9.9K vol, KD 3
  { tier: 'ingredient', title: 'Thiamine (Vitamin B1) Deficiency: Symptoms, Causes, and How to Correct It', category: 'Vitamins', primaryKeyword: 'thiamine vitamin b1 deficiency symptoms', secondaryKeywords: ['thiamine deficiency causes', 'vitamin B1 deficiency signs', 'benfotiamine supplement', 'thiamine for energy', 'B1 neurological symptoms'] },

  // Score 3,009 — 33.1K vol, KD 11
  { tier: 'ingredient', title: 'Magnesium Glycinate Side Effects: What the Research Says About Safety', category: 'Supplements', primaryKeyword: 'magnesium glycinate side effects', secondaryKeywords: ['is magnesium glycinate safe', 'magnesium glycinate too much', 'magnesium glycinate interactions', 'magnesium overdose symptoms', 'magnesium glycinate dosage safety'] },

  // Score 2,775 — 22.2K vol, KD 8
  { tier: 'ingredient', title: 'Magnesium Glycinate for Anxiety: Dosage, Timing, and Clinical Evidence', category: 'Mental Health', primaryKeyword: 'magnesium glycinate for anxiety', secondaryKeywords: ['magnesium glycinate anxiety dosage', 'magnesium and GABA anxiety', 'best magnesium for anxiety', 'magnesium for stress and anxiety', 'magnesium deficiency anxiety'] },

  // Score 2,258 — 27.1K vol, KD 12
  { tier: 'ingredient', title: 'Vitamin C Benefits: The Evidence-Based Case for Higher Doses', category: 'Vitamins', primaryKeyword: 'vitamin c benefits', secondaryKeywords: ['vitamin C immune benefits', 'vitamin C collagen synthesis', 'vitamin C antioxidant benefits', 'high dose vitamin C', 'vitamin C cancer research'] },

  // Score 2,200 — 9.9K vol, KD 2
  { tier: 'ingredient', title: 'Niacin Flush vs No-Flush Niacin: Which Form Is Right for Lipids?', category: 'Vitamins', primaryKeyword: 'niacin vitamin b3 side effects', secondaryKeywords: ['niacin flush remedy', 'inositol hexanicotinate vs niacin', 'niacin for cholesterol', 'nicotinamide riboside vs niacin', 'niacin dosage lipids'] },

  // Score 1,594 — 27.1K vol, KD 17
  { tier: 'ingredient', title: 'L-Glutamine Benefits: Gut, Immunity, and Muscle Recovery Explained', category: 'Supplements', primaryKeyword: 'l-glutamine benefits', secondaryKeywords: ['l-glutamine gut health', 'l-glutamine dosage', 'l-glutamine for leaky gut', 'l-glutamine side effects', 'glutamine muscle recovery'] },

  // Score 1,238 — 49.5K vol, KD 40
  { tier: 'ingredient', title: 'CoQ10 Benefits: The Mitochondrial Molecule Behind Energy and Heart Health', category: 'Supplements', primaryKeyword: 'coenzyme q10 coq10 benefits', secondaryKeywords: ['CoQ10 ubiquinol vs ubiquinone', 'CoQ10 dosage for statins', 'CoQ10 heart health', 'CoQ10 energy supplement', 'coenzyme q10 coq10 side effects'] },

  // Score 1,066 — 40.5K vol, KD 38
  { tier: 'ingredient', title: 'Magnesium Citrate Benefits: The Affordable Magnesium That Still Performs', category: 'Supplements', primaryKeyword: 'magnesium citrate benefits', secondaryKeywords: ['magnesium citrate constipation', 'magnesium citrate bowel prep', 'magnesium citrate vs oxide', 'magnesium citrate absorption', 'magnesium citrate sleep'] },

];

/**
 * Returns clusters not yet represented by titles already in the database.
 * Pass existingTitles (lowercase) to filter out duplicates.
 */
export function getUnusedTopics(existingTitles: string[]): TopicCluster[] {
  const existingSet = new Set(existingTitles.map(t => t.toLowerCase().trim()));
  return TOPIC_CLUSTERS.filter(tc => !existingSet.has(tc.title.toLowerCase().trim()));
}
